public void nullifyUsedVars(){
  bundle=null;
  thecert=null;
  options=null;
  callbackHandler=null;
  amAuthCert_serverHost=null;
  amAuthCert_startSearchLoc=null;
  amAuthCert_securityType=null;
  amAuthCert_principleUser=null;
  amAuthCert_principlePasswd=null;
  amAuthCert_useSSL=null;
  amAuthCert_userProfileMapper=null;
  amAuthCert_altUserProfileMapper=null;
  amAuthCert_chkCRL=null;
  amAuthCert_chkAttrCRL=null;
  amAuthCert_chkAttributesCRL=null;
  amAuthCert_uriParamsCRL=null;
  amAuthCert_chkCertInLDAP=null;
  amAuthCert_chkAttrCertInLDAP=null;
  amAuthCert_emailAddrTag=null;
  portalGateways=null;
  amAuthCert_updateCRL=null;
}
